import type { Metadata } from "next";
import { inter } from "./fonts";
import { playfair_display } from "./fonts";
import "./globals.css";
import Header from "@/components/ui/header";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Kevin Liao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-slate-900`}>
        <div className="hidden absolute z-20 top-0 inset-0 flex justify-center overflow-hidden pointer-events-none h-full">
          <Image src="/backdrop.webp" alt="" fill></Image>
        </div>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
